### PR TITLE
fix missing xml tag in svg flags

### PR DESCRIPTION
**Pull request by BorisDibrov**
Fix this issue - https://github.com/antonioribeiro/countries/issues/167

### CODE REVIEW

**Comment by khamsolt** [comment]
@antonioribeiro 
please i need this fixes

**Comment by antonioribeiro** [comment]
How were those files generated?

**Comment by antonioribeiro** [comment]
@BorisDibrov , @khamsolt , 

By not seeing more files updated than only the icons, I believe the method to update it is not right, so please [read this](https://github.com/antonioribeiro/countries#updating) and update the files the right way.

I'm closing this one for now.

Thank you.

**Comment by khamsolt** [comment]
@antonioribeiro I don't know, but https://github.com/mledoze/countries/tree/master/data hasn't committed anymore. And also the console update command did not fix the problem. @BorisDibrov Could you help us?

**Pull request closed without merging**
