### PR TITLE
france states list fix(earlier it was returning no state list for france country)

### PR DESCRIPTION
**Pull request by ramsyadav**
I have worked on the France state list issue,where when fetching the state list for France it was returning no state list.Now after the fix we can get the states list of France.
This issue was already raised as https://github.com/antonioribeiro/countries/issues/28

### CODE REVIEW

**Comment by Cyrille37** [comment]
Hi,
Please, can you merge this PR or tell us what is missing ?

The travis-ci failed seems to come from another problem:
```
PHP Fatal error:  Class 'PragmaRX\Countries\Tests\PhpUnit\TestCase' not found
in /home/travis/build/antonioribeiro/countries/tests/phpunit/Service/ServiceTest.php on line 9
```

**Comment by antonioribeiro** [comment]
I cannot really merge this PR, not yet at least, because those states are not updatable here (not now). The states data come from https://github.com/nvkelso/natural-earth-vector, and I cannot afford to maintain it here too.

I am making a series of changes to this package so we can have different sets of data.

**Comment by Cyrille37** [comment]
Nice @antonioribeiro ! Thanks for answer.

But I think `data` is a really important piece of you package (people like/love All In One). So perhaps there is a way to facilitate states data update ? Like WikiData as source and couple of scripts for maintenance ... Did you think about that ?

Cheers.

**Comment by antonioribeiro** [comment]
@Cyrille37 , yes, that's why I'm thinking we need to go both ways: get data from natural-earth-vector, since they are doing a really nice job on maintaining everything updated, and it's huge, but also give us the ability to overload whatever errors (or missing stuff) they have.

It would be better if people just contribute there to get the updates here, but that may be too much to ask, as they have a lot more data than we are consuming here.

**Comment by Cyrille37** [comment]
> It would be better if people just contribute there to get the updates here, but that may be too much to ask, as they have a lot more data than we are consuming here.

And it will be much work for this repository maintainer (you :-))

**Comment by Cyrille37** [comment]
Perhaps that if all data come from "natural-earth-vector"  it's enough. Just write that info at top of README (*I previously thought that data come from different sources*).

**Comment by ramsyadav** [comment]
Thank you guys for reply.

**Comment by antonioribeiro** [comment]
New updater is now renaming the France states file to fra.json.

**Pull request closed without merging**
