### PR TITLE
Add support for psr/simple-cache v3

### PR DESCRIPTION
**Pull request by jkudish**

### CODE REVIEW

**Comment by sykezz** [comment]
I'm assuming you're trying to get Laravel 9 support #185.

I've tried your PR. However, bumping `psr/simple-cache:^3.0` doesn't simply fix the issue. As @gwleuverink mentioned, `pragmarx/coollection` and `pragmarx/ia-arr` needs to be updated as well.

```
  Problem 1
    - ramsey/uuid[3.7.0, ..., 3.8.0] require php ^5.4 || ^7.0 -> your php version (8.1.3) does not satisfy that requirement.
    - ramsey/uuid[3.9.0, ..., 3.9.1] require php ^5.4 | ^7 -> your php version (8.1.3) does not satisfy that requirement.
    - Conclusion: don't install laravel/framework v9.2.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.3.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.3.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.4.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.4.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.5.0 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.5.1 (conflict analysis result)
    - Root composer.json requires laravel/framework ^9.2 -> satisfiable by laravel/framework[v9.2.0, ..., 9.x-dev].
    - Conclusion: don't install pragmarx/ia-collection v6.0.3 (conflict analysis result)
    - Conclusion: don't install pragmarx/ia-collection v7.3.0 (conflict analysis result)
    - Root composer.json requires pragmarx/countries dev-patch-1 -> satisfiable by pragmarx/countries[dev-patch-1].
    - Conclusion: don't install ramsey/uuid[4.2.3] | install one of pragmarx/ia-collection[v5.5.33, v7.3.0] (conflict analysis result)
    - Conclusion: don't install pragmarx/ia-collection v5.5.33 (conflict analysis result)
    - pragmarx/countries dev-patch-1 requires pragmarx/coollection >=0.8 -> satisfiable by pragmarx/coollection[v0.8.0, 1.0.x-dev (alias of dev-master)].
    - pragmarx/coollection 1.0.x-dev is an alias of pragmarx/coollection dev-master and thus requires it to be installed too.
    - pragmarx/coollection[dev-master, v0.8.0] require pragmarx/ia-collection ~5.0|~6.0|~7.0 -> satisfiable by pragmarx/ia-collection[v5.5.33, ..., v5.8.35, v6.0.3, v7.3.0].
    - pragmarx/ia-collection[v5.6.0, ..., v5.8.35] require ramsey/uuid ^3.7 -> satisfiable by ramsey/uuid[3.7.0, ..., 3.x-dev].
    - You can only install one version of a package, so only one of these can be installed: ramsey/uuid[dev-main, 3.7.0, ..., 3.x-dev, 4.0.0-alpha1, ..., 4.2.3].
    - ramsey/uuid 4.x-dev is an alias of ramsey/uuid dev-main and thus requires it to be installed too.
    - laravel/framework 9.x-dev requires ramsey/uuid ^4.2.2 -> satisfiable by ramsey/uuid[4.2.2, 4.2.3, 4.x-dev (alias of dev-main)].
    - Conclusion: don't install ramsey/uuid[4.2.2] | install one of pragmarx/ia-collection[v5.5.33, v7.3.0] (conflict analysis result)
 ```

**Comment by gwleuverink** [comment]
If I'm not mistaken also the interface for psr/simple-cache has changed so the implementation needs to be updated too.

Since the contract is changed I don't think you can require both the 2.x & 3.x version of simple-cache. It will probably break backwards compatibility when a project has v2.x locked

**Comment by antonioribeiro** [comment]
Please check comments on https://github.com/antonioribeiro/countries/pull/188

**Comment by antonioribeiro** [comment]
I'm sorry I'm slow on answers here, I'm out of time to manage my packages.

Unfortunately is not as simple as adding the requirement on the countries package, tests also need to pass, but I don't see any PRs adding it and refactoring the code to make it really compatible and make the tests pass.

On a Laravel 9 application, you can add this to your composer.json:

```json
"psr/simple-cache": "^1.0|^2.0",
```

And it should be able to update the countries package and all its dependencies.

Tagging all instances of the same thing here so people can take a look at the current state:

https://github.com/antonioribeiro/countries/pull/195
https://github.com/antonioribeiro/countries/pull/193

**Pull request closed without merging**
